title: DTE-2602 Introduction to machine learning and AI

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: martin.skjelvareid@uit.no
  name: Martin H. Skjelvareid

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
